### ISSUE TITLE
showing error when runing on ubuntu terminal

### ISSUE THREAD

**Issue by deepakkuk** [ahlashkari/ISCXFlowMeter#3]
![screenshot from 2018-11-30 10-11-11](https://user-images.githubusercontent.com/33250220/49268925-4da21e80-f488-11e8-87f1-10637f4b20ec.png)

**Comment by CapSparkle** [comment]
I have the same problem. If you already solve this problem please send it here!

**Comment by deepakkuk** [comment]
> I have the same problem. If you already solve this problem please send it here!

i got preprocessed iscx 2012 dataset through this person via mail 
https://github.com/tamimmirza/Intrusion-Detection-System-using-Deep-Learning/issues/4#issuecomment-442868323
itstamimmirza@gmail.com

**Comment by CapSparkle** [comment]
Good solve) Could you give it to me, please?23.01.2019, 13:03, "deepakkuk" <notifications@github.com>:
I have the same problem. If you already solve this problem please send it here!

i got preprocessed iscx 2012 dataset through this person via mail
tamimmirza/Intrusion-Detection-System-using-Deep-Learning#4 (comment)
itstamimmirza@gmail.com

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением, Андрей Фескович+79526834905

**Comment by deepakkuk** [comment]
> Good solve) Could you give it to me, please?23.01.2019, 13:03, "deepakkuk" <notifications@github.com>: I have the same problem. If you already solve this problem please send it here! i got preprocessed iscx 2012 dataset through this person via mail [tamimmirza/Intrusion-Detection-System-using-Deep-Learning#4](https://github.com/tamimmirza/Intrusion-Detection-System-using-Deep-Learning/issues/4) (comment) itstamimmirza@gmail.com —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
> […](#)
> -- С уважением, Андрей Фескович+79526834905

share your email id

**Comment by CapSparkle** [comment]
Feskovich.a@yandex.com

**Comment by CapSparkle** [comment]
feskovich.a@yandex.com

**Comment by CapSparkle** [comment]
feskovich.a@yandex.comThank you, mery much)23.01.2019, 14:55, "deepakkuk" <notifications@github.com>:
Good solve) Could you give it to me, please?23.01.2019, 13:03, "deepakkuk" notifications@github.com: I have the same problem. If you already solve this problem please send it here! i got preprocessed iscx 2012 dataset through this person via mail tamimmirza/Intrusion-Detection-System-using-Deep-Learning#4 (comment) itstamimmirza@gmail.com —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
…
-- С уважением, Андрей Фескович+79526834905

share your email id

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением, Андрей Фескович+79526834905

**Comment by ahlashkari** [comment]
Hi Folks,
This is the old version. Pls download the CICFlowMeter which is the new version and has 40 features more than this one.
